# Generated by Django 5.0.2 on 2024-03-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_cart_cartcourse_cart_courses_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartcourse',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartcourse',
            name='course',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartCourse',
        ),
    ]
