# Generated by Django 5.0.2 on 2024-03-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='projects',
            field=models.ManyToManyField(related_name='projects', through='cart.CartProject', to='projects.project'),
        ),
    ]
